# sonar-project.properties
sonar.projectKey=nextjs-multizone-tmdb
sonar.organization=fubaritico
sonar.sources=apps
sonar.exclusions=**/node_modules/**,**/dist/**,**/.next/**,**/coverage/**
sonar.javascript.lcov.reportPaths=apps/home/coverage/lcov.info,apps/media/coverage/lcov.info,apps/talents/coverage/lcov.info,apps/search/coverage/lcov.info
